name: latihan_slicing
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # dependencies lainnya...

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # dev_dependencies lainnya...

# Konfigurasikan Flutter di sini
flutter:
  uses-material-design: true

  # Tambahkan assets Anda di sini
  assets:
    - assets/images/